services:
  RedisConnection:
    class: RedisCluster
    factory: [ Symfony\Component\Cache\Adapter\RedisAdapter, createConnection ]
    arguments:
      # Redis DSN
      - 'redis://%env(REDIS_HOST)%:%env(REDIS_PORT)%&redis_cluster=1'
      # Options
      - []