doctrine:
  orm:
    mappings:
      UsersManagement/User:
        type: attribute
        is_bundle: false
        dir: '%kernel.project_dir%/src/Context/UsersManagement/Container/User/Entity'
        prefix: 'App\Context\UsersManagement\Container\User\Entity'
        alias: App