doctrine:
  orm:
    mappings:
      UsersManagement/Request:
        type: attribute
        is_bundle: false
        dir: '%kernel.project_dir%/src/Context/UsersManagement/Container/Request/Entity'
        prefix: 'App\Context\UsersManagement\Container\Request\Entity'
        alias: App